### DISCUSSION TITLE
Should colour use isort?

### DISCUSSION THREAD

**Discussion by tjdcs** [colour-science/colour#1210] [Ideas]
Enforcing code style is useful, but tools like Black and Ruff (by default) won't sort imports according to pep8 style. isort is powerful and maybe unsafe if there is some monkey patching going on, but these concerns should be addressable with the pyproject config. For example:

```toml
[tool.isort]
multi_line_output= 3
include_trailing_comma= true
force_grid_wrap= 0
use_parentheses= true
ensure_newline_before_comments= true
line_length= 88
split_on_trailing_comma= true
```

So should we start using isort in conjunction with black to force formatting of imports? 

My main motivation is to make a tool automatically remove unused imports that sometimes happen when I'm developing and making heavy use of autocomplete, later removing that section of code. As well as to make sure autocomplete imports are being added in the correct location.
